Repository wecode-bootcamp-korea/19-1st-the_meat-backend, pull requests merged in 2021-04, with the labels that each got.

#5 Feature/models
  manage.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/urls.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/urls.py
  products/views.py
  theMeat/asgi.py
  theMeat/settings.py
  theMeat/urls.py
  theMeat/wsgi.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: Accepted

#8 Feature/models
  .DS_Store
  .gitignore
  __pycache__/mysettings.cpython-38.pyc
  orders/.DS_Store
  orders/__pycache__/__init__.cpython-38.pyc
  orders/__pycache__/apps.cpython-38.pyc
  orders/__pycache__/models.cpython-38.pyc
  orders/__pycache__/urls.cpython-38.pyc
  orders/__pycache__/views.cpython-38.pyc
  orders/migrations/0001_initial.py
  orders/migrations/__pycache__/__init__.cpython-38.pyc
  orders/models.py
  orders/urls.py
  orders/views.py
  products/.DS_Store
  products/__pycache__/__init__.cpython-38.pyc
  products/__pycache__/apps.cpython-38.pyc
  products/__pycache__/models.cpython-38.pyc
  products/__pycache__/urls.cpython-38.pyc
  products/__pycache__/views.cpython-38.pyc
  products/migrations/0001_initial.py
  products/migrations/0002_alter_product_original_price.py
  products/migrations/0003_remove_product_unit.py
  products/migrations/__pycache__/0001_initial.cpython-38.pyc
  products/migrations/__pycache__/__init__.cpython-38.pyc
  products/models.py
  products/urls.py
  products/views.py
  theMeat/__pycache__/__init__.cpython-38.pyc
  theMeat/__pycache__/settings.cpython-38.pyc
  theMeat/__pycache__/urls.cpython-38.pyc
  theMeat/__pycache__/wsgi.cpython-38.pyc
  users/.DS_Store
  users/__pycache__/__init__.cpython-38.pyc
  users/__pycache__/apps.cpython-38.pyc
  users/__pycache__/models.cpython-38.pyc
  users/__pycache__/urls.cpython-38.pyc
  users/__pycache__/views.cpython-38.pyc
  users/migrations/0001_initial.py
  users/migrations/0002_alter_userrank_previous_payment.py
  users/migrations/0003_alter_userrank_previous_payment.py
  users/migrations/__pycache__/0001_initial.cpython-38.pyc
  users/migrations/__pycache__/__init__.cpython-38.pyc
  users/models.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#10 Feature/models
  __pycache__/mysettings.cpython-38.pyc
  orders/__pycache__/models.cpython-38.pyc
  orders/__pycache__/urls.cpython-38.pyc
  orders/__pycache__/views.cpython-38.pyc
  orders/migrations/0001_initial.py
  orders/migrations/__pycache__/__init__.cpython-38.pyc
  orders/models.py
  products/__pycache__/models.cpython-38.pyc
  products/__pycache__/urls.cpython-38.pyc
  products/__pycache__/views.cpython-38.pyc
  products/migrations/0001_initial.py
  products/migrations/0002_alter_product_original_price.py
  products/migrations/0003_remove_product_unit.py
  products/migrations/__pycache__/0001_initial.cpython-38.pyc
  products/migrations/__pycache__/__init__.cpython-38.pyc
  products/models.py
  theMeat/__pycache__/settings.cpython-38.pyc
  users/__pycache__/models.cpython-38.pyc
  users/__pycache__/urls.cpython-38.pyc
  users/__pycache__/views.cpython-38.pyc
  users/migrations/0001_initial.py
  users/migrations/0002_alter_userrank_previous_payment.py
  users/migrations/0003_alter_userrank_previous_payment.py
  users/migrations/__pycache__/0001_initial.cpython-38.pyc
  users/migrations/__pycache__/__init__.cpython-38.pyc
  users/models.py
Labels: Status: 리뷰 요청

#13 .gitignore 수정
  .gitignore
Labels: Status: 리뷰 요청

#19 1. .DS_Store removed 2. pycharm gitignore 추가
  .gitignore
  orders/.DS_Store
  products/.DS_Store
  users/.DS_Store
Labels: Status: 리뷰 요청

#17 Add: product filter 생성
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#21 models.py 기존에 original_price가 제대로 호출되지 않던 문제 수정
  products/models.py
Labels: Status: 리뷰 요청

#22 MODIFY: gitignore 수정 및 사진 갯수 수정
  products/__pycache__/urls.cpython-38.pyc
  products/__pycache__/views.cpython-38.pyc
  products/models.py
  products/tests.py
  products/views.py
Labels: Status: 리뷰 요청

#20 로그인, 회원가입 기능
  theMeat/settings.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#9 Feature/cart view
  orders/views.py
  products/__pycache__/urls.cpython-38.pyc
  products/__pycache__/views.cpython-38.pyc
Labels: Status: 리뷰 요청

#23 ADD: filter 기능 추가
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#16 제품 상세페이지 (ProductDetailView) 작성
  data/products.numbers~Stashed changes
  products/urls.py
  products/views.py
Labels: Status: 수정 요청

#24 로그인 데코레이터, address view 작성
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 수정 요청

#25 urls 수정 반영 안된 것 수정. 최근 main merge 완료
  products/urls.py
Labels: Status: 리뷰 요청

#26 Feature/cart view
  orders/urls.py
  orders/views.py
Labels: Status: 리뷰 요청

#28 price format 재수정..! merge 해주세요 승현님...ㅠㅠㅠ
  products/models.py
  products/views.py
Labels: Status: 리뷰 요청
